[user]
name = "Ben Lubas"
email = "benmlubas@gmail.com"

[ui]
pager = "delta"
diff.format = "git"
default-command = ["log", "--limit", "15"]
# using julienvincent/hunk.nvim
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
